CREATE TABLE PERSON(
    RetrosheetID                    varchar2(8) NOT NULL PRIMARY KEY,
    LastName                        varchar2(30),
    FirstName                       varchar2(20),
    UseName                         varchar2(30),
    BirthDate                       date,
    BirthCity                       varchar2(50),
    BirthState                      varchar2(2),
    BirthCountry                    varchar2(30),
    DebutDateAsPlayer               date,
    DateOfLastGameAsPlayer          date,
    DebutDateAsManager              date,
    DateOfLastGameAsManager         date,
    DebutDateAsCoach                date,
    DateOfLastGameAsCoach           date,
    DebutDateAsUmpire               date,
    DateOfLastGameAsUmpire          date,
    DeathDate                       date,
    DeathCity                       varchar2(50),
    DeathState                      varchar2(2),
    DeathCountry                    varchar2(30),
    Bat                             varchar2(1),
    Throws                          varchar2(1),
    Height                          number(2),
    Weight                          number(3),
    Cemetery                        varchar2(30),
    CemeteryCity                    varchar2(50),
    CemeteryState                   varchar2(2),
    CemeteryCountry                 varchar2(30),
    CemeteryNote                    varchar2(250),
    BirthName                       varchar2(50),
    NameChange                      varchar2(100),
    BatChange                       varchar2(100),
    HOF                             varchar2(100)
);