/* 
NOTE: creates the table for gamelogs
*/

-- drop the old table
DROP TABLE GAMELOGS CASCADE CONSTRAINTS;

-- make the table schema
CREATE TABLE GAMELOGS(
    Id                                              VARCHAR2(12) NOT NULL,
    GameDate	                                    DATE,
    GameNumber	                                    VARCHAR2(1),
    DayOfWeek	                                    VARCHAR2(3),
    VisitingTeam	                                VARCHAR2(3),
    VisitingLeague	                                VARCHAR2(2),
    VisitingGameNumber	                            INTEGER,
    HomeTeam	                                    VARCHAR2(3),
    HomeLeague	                                    VARCHAR2(2),
    HomeGameNumber	                                INTEGER,
    VisitingScore	                                INTEGER,
    HomeScore	                                    INTEGER,
    LengthInOuts	                                INTEGER,
    DayOrNight	                                    VARCHAR2(1),
    CompletionInformation	                        VARCHAR2(25),
    ForfeitInformation	                            VARCHAR2(1),
    ProtestInformation	                            VARCHAR2(1),
    ParkId	                                        VARCHAR2(5),
    Attendance	                                    INTEGER,
    TimeInMinutes	                                INTEGER,
    VisitingLineScore	                            VARCHAR2(35),
    HomeLineScore	                                VARCHAR2(35),
    VisitingAtBats	                                INTEGER,
    VisitingHits	                                INTEGER,
    VisitingDoubles	                                INTEGER,
    VisitingTriples	                                INTEGER,
    VisitingHomeRuns	                            INTEGER,
    VisitingRBI	                                    INTEGER,
    VisitingSacrificeHits	                        INTEGER,
    VisitingSacrificeFlies	                        INTEGER,
    VisitingHitByPitch	                            INTEGER,
    VisitingWalks	                                INTEGER,
    VisitingIntentionalWalks	                    INTEGER,
    VisitingStrikeouts	                            INTEGER,
    VisitingStolenBases	                            INTEGER,
    VisitingCaughtStealing	                        INTEGER,
    VisitingGroundIntoDoublePlays	                INTEGER,
    VisitingAwardedFirstOnCatchInt             	    INTEGER,
    VisitingLeftOnBase	                            INTEGER,
    VisitingPitchersUsed	                        INTEGER,
    VisitingIndividualEarnedRuns	                INTEGER,
    VisitingTeamEarnedRuns	                        INTEGER,
    VisitingWildPitches	                            INTEGER,
    VisitingBalks	                                INTEGER,
    VisitingPutouts	                                INTEGER,
    VisitingAssists	                                INTEGER,
    VisitingErrors	                                INTEGER,
    VisitingPassedBalls	                            INTEGER,
    VisitingDoublePlays	                            INTEGER,
    VisitingTriplePlays	                            INTEGER,
    HomeAtBats	                                    INTEGER,
    HomeHits	                                    INTEGER,
    HomeDoubles	                                    INTEGER,
    HomeTriples	                                    INTEGER,
    HomeHomeRuns	                                INTEGER,
    HomeRBI	                                        INTEGER,
    HomeSacrificeHits	                            INTEGER,
    HomeSacrificeFlies	                            INTEGER,
    HomeHitByPitch	                                INTEGER,
    HomeWalks	                                    INTEGER,
    HomeIntentionalWalks	                        INTEGER,
    HomeStrikeouts	                                INTEGER,
    HomeStolenBases	                                INTEGER,
    HomeCaughtStealing	                            INTEGER,
    HomeGroundIntoDoublePlays	                    INTEGER,
    HomeAwardedFirstOnCatchInt           	        INTEGER,
    HomeLeftOnBase	                                INTEGER,
    HomePitchersUsed	                            INTEGER,
    HomeIndividualEarnedRuns	                    INTEGER,
    HomeTeamEarnedRuns	                            INTEGER,
    HomeWildPitches	                                INTEGER,
    HomeBalks	                                    INTEGER,
    HomePutouts	                                    INTEGER,
    HomeAssists	                                    INTEGER,
    HomeErrors	                                    INTEGER,
    HomePassedBalls	                                INTEGER,
    HomeDoublePlays	                                INTEGER,
    HomeTriplePlays	                                INTEGER,
    HomePlateUmpireId	                            VARCHAR2(8),
    FirstBaseUmpireId	                            VARCHAR2(8),
    SecondBaseUmpireId	                            VARCHAR2(8),
    ThirdBaseUmpireId	                            VARCHAR2(8),
    LfUmpireId	                                    VARCHAR2(8),
    RfUmpireId	                                    VARCHAR2(8),
    VisitingTeamManagerId	                        VARCHAR2(8),
    HomeTeamManagerId	                            VARCHAR2(8),
    WinningPitcherId	                            VARCHAR2(8),
    LosingPitcherId	                                VARCHAR2(8),
    SavingPitcherId	                                VARCHAR2(8),
    GameWinningRBIBatterId	                        VARCHAR2(8),
    VisitingStartingPitcherId	                    VARCHAR2(8),
    HomeStartingPitcherId	                        VARCHAR2(8),
    VisitingStartingPlayer1Id	                    VARCHAR2(8),
    VisitingStartingPlayer1Pos                      VARCHAR2(2),
    VisitingStartingPlayer2Id	                    VARCHAR2(8),
    VisitingStartingPlayer2Pos  	                VARCHAR2(2),
    VisitingStartingPlayer3Id	                    VARCHAR2(8),
    VisitingStartingPlayer3Pos  		            VARCHAR2(2),
    VisitingStartingPlayer4Id	                    VARCHAR2(8),
    VisitingStartingPlayer4Pos  		            VARCHAR2(2),
    VisitingStartingPlayer5Id	                    VARCHAR2(8),
    VisitingStartingPlayer5Pos  	                VARCHAR2(2),
    VisitingStartingPlayer6Id	                    VARCHAR2(8),
    VisitingStartingPlayer6Pos  	                VARCHAR2(2),
    VisitingStartingPlayer7Id	                    VARCHAR2(8),
    VisitingStartingPlayer7Pos  	                VARCHAR2(2),
    VisitingStartingPlayer8Id	                    VARCHAR2(8),
    VisitingStartingPlayer8Pos  	                VARCHAR2(2),
    VisitingStartingPlayer9Id	                    VARCHAR2(8),
    VisitingStartingPlayer9Pos  	                VARCHAR2(2),
    HomeStartingPlayer1Id	                        VARCHAR2(8), 
    HomeStartingPlayer1Pos  	                    VARCHAR2(2),
    HomeStartingPlayer2Id	                        VARCHAR2(8), 
    HomeStartingPlayer2Pos  	                    VARCHAR2(2),
    HomeStartingPlayer3Id	                        VARCHAR2(8), 
    HomeStartingPlayer3Pos  	                    VARCHAR2(2),
    HomeStartingPlayer4Id	                        VARCHAR2(8), 
    HomeStartingPlayer4Pos  	                    VARCHAR2(2),
    HomeStartingPlayer5Id	                        VARCHAR2(8), 
    HomeStartingPlayer5Pos  	                    VARCHAR2(2),
    HomeStartingPlayer6Id	                        VARCHAR2(8), 
    HomeStartingPlayer6Pos  	                    VARCHAR2(2),
    HomeStartingPlayer7Id	                        VARCHAR2(8), 
    HomeStartingPlayer7Pos  	                    VARCHAR2(2),
    HomeStartingPlayer8Id	                        VARCHAR2(8), 
    HomeStartingPlayer8Pos  	                    VARCHAR2(2),
    HomeStartingPlayer9Id	                        VARCHAR2(8), 
    HomeStartingPlayer9Pos  	                    VARCHAR2(2),
    AdditionalInformation	                        VARCHAR2(500),
    AquisitionInformation                           VARCHAR2(1)
);

-- add the PK to the table
ALTER TABLE GAMELOGS ADD CONSTRAINT GAMELOGS_PK PRIMARY KEY (Id);

-- create ref
CREATE OR REPLACE PUBLIC SYNONYM gamelogs FOR admin.gamelogs;

-- after that commit all of the changes made
COMMIT;