/* 
NOTE: creates the table for gamelogs
*/

-- drop the old table
DROP TABLE gamelogs CASCADE CONSTRAINTS;

-- make the table schema
CREATE TABLE gamelogs (
    gameid VARCHAR2 (12) NOT NULL,
    gamedate date,
    gamenumber VARCHAR2 (1),
    dayofweek VARCHAR2 (3),
    visitingteam VARCHAR2 (3),
    visitingleague VARCHAR2 (2),
    visitinggamenumber INTEGER,
    hometeam VARCHAR2 (3),
    homeleague VARCHAR2 (2),
    homegamenumber INTEGER,
    visitingscore INTEGER,
    homescore INTEGER,
    lengthinouts INTEGER,
    dayornight VARCHAR2 (1),
    completioninformation VARCHAR2 (25),
    forfeitinformation VARCHAR2 (1),
    protestinformation VARCHAR2 (1),
    parkid VARCHAR2 (5),
    attendance INTEGER,
    timeinminutes INTEGER,
    visitinglinescore VARCHAR2 (35),
    homelinescore VARCHAR2 (35),
    visitingatbats INTEGER,
    visitinghits INTEGER,
    visitingdoubles INTEGER,
    visitingtriples INTEGER,
    visitinghomeruns INTEGER,
    visitingrbi INTEGER,
    visitingsacrificehits INTEGER,
    visitingsacrificeflies INTEGER,
    visitinghitbypitch INTEGER,
    visitingwalks INTEGER,
    visitingintentionalwalks INTEGER,
    visitingstrikeouts INTEGER,
    visitingstolenbases INTEGER,
    visitingcaughtstealing INTEGER,
    visitinggroundintodoubleplays INTEGER,
    visitingawardedfirstoncatchint INTEGER,
    visitingleftonbase INTEGER,
    visitingpitchersused INTEGER,
    visitingindividualearnedruns INTEGER,
    visitingteamearnedruns INTEGER,
    visitingwildpitches INTEGER,
    visitingbalks INTEGER,
    visitingputouts INTEGER,
    visitingassists INTEGER,
    visitingerrors INTEGER,
    visitingpassedballs INTEGER,
    visitingdoubleplays INTEGER,
    visitingtripleplays INTEGER,
    homeatbats INTEGER,
    homehits INTEGER,
    homedoubles INTEGER,
    hometriples INTEGER,
    homehomeruns INTEGER,
    homerbi INTEGER,
    homesacrificehits INTEGER,
    homesacrificeflies INTEGER,
    homehitbypitch INTEGER,
    homewalks INTEGER,
    homeintentionalwalks INTEGER,
    homestrikeouts INTEGER,
    homestolenbases INTEGER,
    homecaughtstealing INTEGER,
    homegroundintodoubleplays INTEGER,
    homeawardedfirstoncatchint INTEGER,
    homeleftonbase INTEGER,
    homepitchersused INTEGER,
    homeindividualearnedruns INTEGER,
    hometeamearnedruns INTEGER,
    homewildpitches INTEGER,
    homebalks INTEGER,
    homeputouts INTEGER,
    homeassists INTEGER,
    homeerrors INTEGER,
    homepassedballs INTEGER,
    homedoubleplays INTEGER,
    hometripleplays INTEGER,
    homeplateumpireid VARCHAR2 (8),
    firstbaseumpireid VARCHAR2 (8),
    secondbaseumpireid VARCHAR2 (8),
    thirdbaseumpireid VARCHAR2 (8),
    lfumpireid VARCHAR2 (8),
    rfumpireid VARCHAR2 (8),
    visitingteammanagerid VARCHAR2 (8),
    hometeammanagerid VARCHAR2 (8),
    winningpitcherid VARCHAR2 (8),
    losingpitcherid VARCHAR2 (8),
    savingpitcherid VARCHAR2 (8),
    gamewinningrbibatterid VARCHAR2 (8),
    visitingstartingpitcherid VARCHAR2 (8),
    homestartingpitcherid VARCHAR2 (8),
    visitingstartingplayer1id VARCHAR2 (8),
    visitingstartingplayer1pos VARCHAR2 (2),
    visitingstartingplayer2id VARCHAR2 (8),
    visitingstartingplayer2pos VARCHAR2 (2),
    visitingstartingplayer3id VARCHAR2 (8),
    visitingstartingplayer3pos VARCHAR2 (2),
    visitingstartingplayer4id VARCHAR2 (8),
    visitingstartingplayer4pos VARCHAR2 (2),
    visitingstartingplayer5id VARCHAR2 (8),
    visitingstartingplayer5pos VARCHAR2 (2),
    visitingstartingplayer6id VARCHAR2 (8),
    visitingstartingplayer6pos VARCHAR2 (2),
    visitingstartingplayer7id VARCHAR2 (8),
    visitingstartingplayer7pos VARCHAR2 (2),
    visitingstartingplayer8id VARCHAR2 (8),
    visitingstartingplayer8pos VARCHAR2 (2),
    visitingstartingplayer9id VARCHAR2 (8),
    visitingstartingplayer9pos VARCHAR2 (2),
    homestartingplayer1id VARCHAR2 (8),
    homestartingplayer1pos VARCHAR2 (2),
    homestartingplayer2id VARCHAR2 (8),
    homestartingplayer2pos VARCHAR2 (2),
    homestartingplayer3id VARCHAR2 (8),
    homestartingplayer3pos VARCHAR2 (2),
    homestartingplayer4id VARCHAR2 (8),
    homestartingplayer4pos VARCHAR2 (2),
    homestartingplayer5id VARCHAR2 (8),
    homestartingplayer5pos VARCHAR2 (2),
    homestartingplayer6id VARCHAR2 (8),
    homestartingplayer6pos VARCHAR2 (2),
    homestartingplayer7id VARCHAR2 (8),
    homestartingplayer7pos VARCHAR2 (2),
    homestartingplayer8id VARCHAR2 (8),
    homestartingplayer8pos VARCHAR2 (2),
    homestartingplayer9id VARCHAR2 (8),
    homestartingplayer9pos VARCHAR2 (2),
    additionalinformation VARCHAR2 (500),
    aquisitioninformation VARCHAR2 (1)
);

-- add the PK to the table
ALTER TABLE gamelogs ADD CONSTRAINT gamelogs_pk PRIMARY KEY (id);

-- create ref
CREATE OR REPLACE PUBLIC SYNONYM gamelogs FOR admin.gamelogs;

-- after that commit all of the changes made
COMMIT;